---
title: "Classification For Predicting Multi-level Product Categories"
subtitle: "R-Code - EDA"
output:
  pdf_document: 
    fig_caption: yes
  word_document: default
  html_document:
  df_print: paged

---
  
$\vspace{-0.5cm}$

```{r, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, 
                      fig.pos = 'H',fig.height=3, fig.width=10, 
                      fig.path='figure/graphics-',
                      cache.path='cache/graphics-', 
                      fig.align='center', external=TRUE)
                 
```

```{r ref.label=knitr::all_labels(), eval=FALSE, echo=TRUE}

 

```


```{r}

#Necessary libraries.
if (!require('kableExtra')) install.packages('kableExtra'); library('kableExtra')
if (!require('e1071')) install.packages('e1071'); library('e1071')
#if (!require('MASS')) install.packages("MASS"); library('MASS')
if (!require('lars')) install.packages("lars"); library('lars')
if (!require('pls')) install.packages("pls"); library('pls')
if (!require('ggplot2')) install.packages('ggplot2'); library('ggplot2')
if (!require('dplyr')) install.packages('dplyr'); library('dplyr')
if (!require('class')) install.packages('class'); library('class')
if (!require('tidyverse')) install.packages('tidyverse'); library('tidyverse')
if (!require('FSelectorRcpp')) install.packages('FSelectorRcpp'); library('FSelectorRcpp')
if (!require('reshape2')) install.packages('reshape2');library('reshape2') #used for melt
if (!require('ggcorrplot')) install.packages("ggcorrplot"); library('ggcorrplot')
if (!require('corrplot')) install.packages("corrplot"); library('corrplot')
if (!require('leaps')) install.packages("leaps"); library('leaps')
if (!require("gridExtra")) install.packages("gridExtra");library(gridExtra)
if (!require("ggpubr")) install.packages("ggpubr");library(ggpubr)
if (!require("xtable")) install.packages("ggpubr");library(xtable)

```

```{r}
# Functions
statistics <- function(data, digits = 3, title = "Summary statistics"){
  data <- data %>% select_if(is.numeric)
  n = seq(1,4*length(data),1)
  table <- data %>% setNames(gsub("_","-",names(.))) %>%
    summarise_all(list(~min(., na.rm = T), ~mean(., na.rm = T), 
                       ~median(., na.rm = T),~max(., na.rm = T))) %>%
  pivot_longer(n,names_to = "measure", values_to = "value") %>% 
  separate(measure, c("var", "statistic"), sep = "\\_") %>%
  pivot_wider(names_from = var, values_from = value) %>%
  column_to_rownames('statistic') %>%    t(.) %>% data.frame() %>%
  kable(caption = title, digits = digits, align = "l",
        col.names = c("Min", "Mean", "Median", "Max") ) %>%
    kable_styling("striped", full_width = T, 
      latex_options = c("HOLD_position")) %>% row_spec (row = 0, bold = T)
  return(table)
}


```


```{r}
train = read.csv("./Data/train.csv",header = T)
nonzero_count = apply(train[,2:ncol(train)-1],1,function(row){sum(row>0)})
nonzero_total = apply(train[,2:ncol(train)-1],1,sum)

train = train[,c(95,2:94)]
train$nonzero_count = nonzero_count
train$nonzero_total = nonzero_total-1

train$target = as.factor(train$target)
```



```{r}
library(scales)

class_dist = train %>% ggplot(aes(x = factor(target), 
                          y = prop.table(stat(count)), 
                          label = scales::percent(prop.table(stat(count))))) +
    geom_bar(position = "dodge") + 
    geom_text(stat = 'count',
              position = position_dodge(.9), 
              vjust = -0.5, 
              size = 3) + 
    scale_y_continuous(labels = scales::percent) + 
    labs(x = 'Class', y = 'Percentage')

```
```{r}
library(vtable)
p = st(train, title="",c("feat_1", "feat_2", "feat_3", "feat_5", 
"feat_88", "feat_89","feat_90","feat_91", "feat_92", "feat_93"), out="kable")

```

```{r fig.height=15}
corrplot(cor(train[-c(1,95,96)]), t1.cex=0.5, cl.cex = 0.5)
```


```{r mean_of_means}

min_of_means = min(apply(train[,-c(1,95,96)],2,mean))
max_of_means = max(apply(train[,-c(1,95,96)],2,mean))
median_of_means = median(apply(train[,-c(1,95,96)],2,mean))

min_of_medians = min(apply(train[,-c(1,95,96)],2,median))
max_of_medians = max(apply(train[,-c(1,95,96)],2,median))
median_of_medians = median(apply(train[,-c(1,95,96)],2,median))

min_of_variance = min(apply(train[,-c(1,95,96)],2,var))
max_of_variance = max(apply(train[,-c(1,95,96)],2,var))
median_of_variance = median(apply(train[,-c(1,95,96)],2,var))


```


```{r}

library(e1071)
ske = as.data.frame(sapply(train[,-1], function(x) c(means = mean(x), 
                                                     vars = var(x), skews = skewness(x))))
t(ske)
```

```{r, fig.height=6}

p1 = qplot(target,feat_1,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333", 
                           size = 6, angle = 90))
p2 = qplot(target,feat_11,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))
p3 = qplot(target,feat_16,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333", size = 6, angle = 90))

p4 = qplot(target,feat_25,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))
p5 = qplot(target,feat_51,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333", size = 6, angle = 90))

p6 = qplot(target,feat_6,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))

p7 = qplot(target,feat_54,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))

p8 = qplot(target,feat_65,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))

p9 = qplot(target,feat_93,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",
                           size = 6, angle = 90))

grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, p9, ncol=3)
```

```{r}
train %>%
  group_by(target) %>%
  summarise(cnt = n()) %>%
  mutate(freq = round(cnt / sum(cnt), 3)) %>% 
  arrange(desc(freq)) %>% kable(caption = "Class Distribution - Train data", 
                                digits = 2, align = "l",
                                col.names = c("Class", "Count", "Freq") ) %>%
                          kable_styling("striped", full_width = T, 
                                latex_options = c("HOLD_position")) %>% 
  row_spec (row = 0, bold = T) 
```


```{r}
qplot(target,nonzero_count,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",size = 8, angle = 90))

qplot(target,nonzero_total,data=train,geom="boxplot") + 
  theme(axis.text.x = element_text(face = "bold", color = "#993333",size = 8, angle = 90))

ggplot(train) + 
    geom_density(aes(x=nonzero_count, colour=target))

ggplot(train) + 
    geom_density(aes(x=nonzero_total, colour=target))

```


```{r}
# strip off ID field
eda.df <- data.frame(target=train$target,train[,2:(ncol(train)-1)])
#augment features with number of features with non-zero counts and total counts
nz.count <- apply(eda.df[,2:ncol(eda.df)],1,function(row){sum(row>0)})
```


```{r fig.width=10}
require(reshape2)
df = apply(train[,2:ncol(train)-1],2,function(col){table(col==0)/length(col)})
df = as.data.frame(sapply(df,"[[",1)) %>% 
     setNames( c("emp_prob")) %>% 
     filter(!row_number() %in% c(1)) 

ggplot(df,aes(rownames(df),emp_prob)) + geom_point() + 
  labs(x="Feature", y="Emp Probability") + 
  theme(axis.text.x = element_text(face = "bold", 
                                   color = "#993333",size = 8, angle = 90))
#df %>% ggplot(aes(x=as.factor(row.names()), y="Emp Probabilities")) + geom_bar()


```





